spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://db:5432/budgee_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: "classpath:db/master.xml"